// javascript

let quotes = ["Be aware, be focused, and be determined. ","The only natural sweetener that god gave man is honey. Everything else is processed.","Ask yourself - how frequently was honey available to our ancestors?","Where were the grains when our people traversed the great Sahara!?! ","Where were the meats when we staved off the winter cold!?","Our modern society has given is convenience at the cost of health and independence! ","Most no longer even know how to source their own food. ","We are at war!!!","Another conspiracy of the modern world! ","Why do we need a long life? What is the purpose of a long life? ","Our ancestors lived as the leaves from the trees. They rose, they procreated, and they died! ","Why be so old and fragile that a single projectile from the anus causes whole body contusions? ","Why be so old and mentally dilapidated that you pray for death because you watched your brother, your sister, and maybe your children die!? ","Death is a gift! A reprieve from the social, cultural, mental, and physical pain of the world! ","Why was suicide practically unheard of in antiquity?","Why was suicide practically unheard of in antiquity? Why is it that when suicide was done, it was ritual and not a mental or health crisis (Vikings went to Valhalla, Japanese Seppuku, Spartan death on the battlefield, Romans dying in the colosseum for glory!)?","Now you can live longer only to live in agony, debt, suffering, hate, and greed!","Be aware, be focused, and be determined. ","The only natural sweetener that god gave man is honey. Everything else is processed.","Ask yourself - how frequently was honey available to our ancestors?","Where were the grains when our people traversed the great Sahara!?! ","Where were the meats when we staved off the winter cold!?","Our modern society has given is convenience at the cost of health and independence! ","Most no longer even know how to source their own food.","We are being systematically lied to about how we are supposed to eat. ","Our ancestors fed upon the flesh of animals only occasionally. Having to hunt, skin, and gut the animal was a laborious process that required knowledge and tools. ","Fishing was more common but seasonal due to the freezing of the weather. Grains were only consumed after harvest and much of it fed cattle or fowl for meat consumption. ","In the modern era we've been pumped full of sugar (a drug), inflammatory inducing hormones in our meats (drug), and toxic metals due to environmental pollution.","We have to take back our food from those who would enslave us to cookies and cakes. ","Do not be fooled my family.","Protect 'yer freedoms","Resist"]
const quote = document.querySelector("#quote")

document.getElementById("gunBtn").addEventListener("click", function getRandomQuote() {
    let index = Math.floor(Math.random() * quotes.length + 1 )
    quote.innerHTML = `"${quotes[index]}"`  
} )



